### ISSUE TITLE
Hom get information from geoname_id

### ISSUE THREAD

**Issue by remydev** [delef/geoip2.cr#3]
Thanks for the fix, this works great !

Do you have a easy way to get geo information from only the geoname_id ?
I think it's better to store juste the geoname_id and get properties when i need it.

However I don't have the background to know if with the updates of the database, the datas change. Do you have an opinion ?

anyway, Good job

**Comment by delef** [comment]
The same question from another repository:
https://github.com/maxmind/GeoIP2-java/issues/103
